function b = bpftry
%BPFTRY Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 09-Oct-2018 08:59:06

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 1600;  % Sampling Frequency

Fstop1 = 1;              % First Stopband Frequency
Fpass1 = 4;             % First Passband Frequency
Fpass2 = 10;             % Second Passband Frequency
Fstop2 = 15;             % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.001;           % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
    1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
